# Generated by Django 3.1.5 on 2021-01-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='blog_type',
            new_name='thread_type',
        ),
    ]
