# Generated by Django 3.1.5 on 2021-01-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
